#!/usr/bin/env bash

# ensure that xpath is available to us
if ! command -v xpath &> /dev/null
then
    sudo apt update && sudo apt install libxml-xpath-perl -y
fi

xml=$1
path=$2
if [ -f "$xml" ]; then
  value=$(xpath -e "$path" "$xml" | perl -pe 's/^.+?\>//; s/\<.+?$//;')
  echo -n "$value"
else
  echo "Invalid xml file '$xml'!"
  exit 1;
fi
