name: Setup Java
description: Action used to setup a Java environment

inputs:
  java_version:
    description: Java version
    required: true
    default: "no"

runs:
  using: composite
  steps:
    - name: Set up JDK ${{ inputs.java_version }}
      uses: actions/setup-java@v3
      with:
        java-version: "${{ inputs.java_version }}"
        distribution: "temurin"
        cache: maven
