name: Setup Java
description: Action used to setup a Java environment

inputs:
  grpc:
    description: If the project uses grpc
    required: true
    default: "no"

runs:
  using: composite
  steps:
    - name: Set up JDK ${{ inputs.jdk_version }}
      uses: actions/setup-java@v3
      with:
        java-version: "${{ inputs.jdk_version }}"
        distribution: "temurin"
        cache: maven
