[package]
name = "init-conf"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
pub-sub = "2.0.0"
run_script = "0.10.1"
serde = { version = "1.0.163", features = ["derive"] }
serde_yaml = "0.9.21"
