version: "3.9"

x-logging:
  &default-logging
  driver: json-file
  options:
    max-size: 10m

networks:
  prod:
    external: true

services:
  log-storage-server:
    image: tobiaszimmer/log-storage-server:0.1.0
    environment:
      STORAGE_SERVER_URI: "0.0.0.0:7888"
      CONTAINER_BLACKLIST: "mongo"
      MONGO_CONNECTION_STR: "mongodb://user:pass@mongodb:27017"
    logging: *default-logging
    networks:
      - prod

  log-watcherd:
    image: tobiaszimmer/log-watcherd:0.1.0
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    environment:
      STORAGE_SERVER_URI: "log-storage-server:7888"
      CONTAINERS_LOCATION: "/var/lib/docker/containers"
    logging: *default-logging
    depends_on:
      - log-storage-server
    networks:
      - prod
