version: "3.9"

x-logging:
  &default-logging
  driver: json-file
  options:
    max-size: 10m

networks:
  prod:
    external: true

services:
  log-storage-server:
    container_name: log-storage-server
    image: tobiaszimmer/log-storage-server:develop-0.1.0-snapshot
    restart: on-failure
    ports:
      - "8000:8000"
    environment:
      STORAGE_SERVER_URI: "0.0.0.0:7888"
      CONTAINER_BLACKLIST: "mongo"
      MONGO_CONNECTION_STR: "mongodb://mongo-router-1:27017"
      AUTH_SERVER_URL: "auth-service:9090"
      RUST_LOG: debug
    logging: *default-logging
    networks:
      - prod
    healthcheck:
      test: curl --fail http://localhost:8000/ping
      interval: 5s
      timeout: 5s
      retries: 5

  log-watcherd:
    container_name: log-watcherd
    image: tobiaszimmer/log-watcherd:develop-0.1.0-snapshot
    restart: on-failure
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    environment:
      STORAGE_SERVER_URI: "log-storage-server:7888"
      CONTAINERS_LOCATION: "/var/lib/docker/containers"
      RUST_LOG: debug
    logging: *default-logging
    depends_on:
      log-storage-server:
        condition: service_healthy
    networks:
      - prod

  logging-view:
    container_name: logging-view
    image: tobiaszimmer/logging-view:develop-0.1.0-snapshot
    restart: on-failure
    ports:
      - "3000:3000"
    environment:
      LOG_SERVICE_URL: "http://log-storage-server:8000"
    logging: *default-logging
    networks:
      - prod
    depends_on:
      log-storage-server:
        condition: service_healthy
