version: "3.9"

x-logging:
  &default-logging
  driver: json-file
  options:
    max-size: 10m

networks:
  prod:
    external: true

services:
  data-importer:
    image: tobiaszimmer/data-importer:main-0.0.1-SNAPSHOT
    restart: on-failure
    logging: *default-logging
    networks:
      - prod
    environment:
      - MSSQL_USERNAME=sa
      - MSSQL_PASSWORD=thisIsSuperStrong1234
      - MSSQL_CONNECTION_STR=jdbc:sqlserver://mssql:1433;databaseName=youbook;trustServerCertificate=true
