version: "3.9"

x-logging:
  &default-logging
  driver: json-file
  options:
    max-size: 10m

services:
  mongodb:
    image: mongo:6.0.5
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    logging: *default-logging
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 40s

  log-watcherd:
    image: tobiaszimmer/log-watcherd:develop-0.1.0-snapshot
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
    environment:
      STORAGE_SERVER_URI: "log-storage-server:7888"
      CONTAINERS_LOCATION: "/var/lib/docker/containers"
    logging: *default-logging
    depends_on:
      - log-storage-server

  log-storage-server:
    image: tobiaszimmer/log-storage-server:develop-0.1.0-snapshot
    environment:
      STORAGE_SERVER_URI: "0.0.0.0:7888"
      CONTAINER_BLACKLIST: "mongo"
      MONGO_CONNECTION_STR: "mongodb://user:pass@mongodb:27017"
    ports:
      - "8000:8000"
    logging: *default-logging
    depends_on:
      mongodb:
        condition: service_healthy

  test-server:
    image: tobiaszimmer/exam-camunda-server:main-1.0.1-release
    environment:
      SERVER_PORT: 8000
    logging: *default-logging
    depends_on:
      - log-watcherd
      - log-storage-server
