version: '3.9'

volumes:
  mongo-storage:

services:
  mongodb:
    image: mongo:6.0.5
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - "mongo-storage:/data/db"
