version: '3.9'

volumes:
  mongo-storage:

services:
  mongodb:
    image: mongo:6.0.5
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - "mongo-storage:/data/db"
  auth-service:
    image: tobiaszimmer/auth-service:test-0.1.0-snapshot
    ports:
      - "9090:9090"
    environment:
      REDIS_HOST: localhost
      REDIS_PORT: 6379
