version: '3.9'

volumes:
  mongo-storage:

services:
  mongodb:
    image: mongo:6.0.5
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
    volumes:
      - "mongo-storage:/data/db"
  auth-service:
    image: tobiaszimmer/auth-service:test-0.1.0-snapshot
    ports:
      - "9090:9090"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      MSSQL_USERNAME: sa
      MSSQL_PASSWORD: thisIsSuperStrong1234
      MSSQL_CONNECTION_STR: "jdbc:sqlserver://mssql:1433;trustServerCertificate=true"
    depends_on:
      redis:
        condition: service_healthy
      mssql:
        condition: service_healthy
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - '6379:6379'
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 1s
      timeout: 3s
      retries: 5
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: thisIsSuperStrong1234
      SA_PASSWORD: thisIsSuperStrong1234
    ports:
      - "1433:1433"
    healthcheck:
      interval: 10s
      timeout: 5s
      start_period: 10s
      retries: 10
      test: '/opt/mssql-tools/bin/sqlcmd -U sa -P "thisIsSuperStrong1234" -Q "SELECT \"READY\"" | grep -q "READY"'
