version: "3.9"

x-logging:
  &default-logging
  driver: json-file
  options:
    max-size: 10m

networks:
  prod:
    external: true

services:
  # config
  mongo-config1:
    container_name: "mongo-config1"
    restart: on-failure
    image: mongo:6.0.5
    command: mongod --port 27017 --configsvr --replSet config-replicaset
    logging: *default-logging
    volumes:
      - "./config/configsvr/config.js:/scripts/mongo-init.js:ro"
    networks:
      - prod

  # shard 1
  mongo-shard1-svr1:
    container_name: "mongo-shard1-svr1"
    restart: on-failure
    image: mongo:6.0.5
    command: mongod --port 27018 --shardsvr --replSet shardsvr1
    logging: *default-logging
    volumes:
      - "./config/shardsvr1/config.js:/scripts/mongo-init.js:ro"
    networks:
      - prod
  mongo-shard1-svr2:
    container_name: "mongo-shard1-svr2"
    restart: on-failure
    image: mongo:6.0.5
    command: mongod --port 27018 --shardsvr --replSet shardsvr1
    logging: *default-logging
    networks:
      - prod

  # shard 2
  mongo-shard2-svr1:
    container_name: "mongo-shard2-svr1"
    restart: on-failure
    image: mongo:6.0.5
    command: mongod --port 27019 --shardsvr --replSet shardsvr2
    logging: *default-logging
    volumes:
      - "./config/shardsvr2/config.js:/scripts/mongo-init.js:ro"
    networks:
      - prod
  mongo-shard2-svr2:
    container_name: "mongo-shard2-svr2"
    restart: on-failure
    image: mongo:6.0.5
    command: mongod --port 27019 --shardsvr --replSet shardsvr2
    logging: *default-logging
    networks:
      - prod

  # router
  mongo-router-1:
    container_name: "mongo-router-1"
    restart: on-failure
    image: mongo:6.0.5
    command: mongos --port 27017 --configdb config-replicaset/mongo-config1:27017 --bind_ip_all
    logging: *default-logging
    ports:
      - "27016:27017"
    networks:
      - prod
    volumes:
      - "./config/router/config.js:/scripts/mongo-init.js:ro"
    depends_on:
      - mongo-config1
      - mongo-shard1-svr1
      - mongo-shard1-svr2
      - mongo-shard2-svr1
      - mongo-shard2-svr2
